# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1ff0b5ba-18e1-43db-8616-ea0b25e00867";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-52846d5d-f14e-4e5f-a167-fe1ff015b9ca".device = "/dev/disk/by-uuid/52846d5d-f14e-4e5f-a167-fe1ff015b9ca";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E623-8214";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp58s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  
  # Dell G15 特定配置
  # 如果有 NVIDIA 显卡，取消下面的注释并配置
  # 首先运行: lspci | grep -E "VGA|3D" 来找到正确的 bus ID
  # hardware.nvidia = {
  #   modesetting.enable = true;
  #   powerManagement.enable = true;
  #   prime = {
  #     sync.enable = true;  # 或使用 offload.enable = true; 以节省电量
  #     # 需要根据实际硬件填写 PCI bus ID
  #     intelBusId = "PCI:0:2:0";
  #     nvidiaBusId = "PCI:1:0:0";
  #   };
  # };
  # services.xserver.videoDrivers = [ "nvidia" ];
}
